# Generated by Django 3.1 on 2020-08-29 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_per_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField(default=100)),
                ('cash_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_.profile')),
            ],
        ),
    ]
