# Generated by Django 3.1 on 2020-09-01 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_', '0002_cash_per_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
